apiVersion: v1
kind: ConfigMap
metadata:
  name: clic-kiusys-api-config
  namespace: clic-kiusys
data:
  ENVIRONMENT: "produccion"
  CLOUD_PROVIDER: "oci"
  OKE_CLUSTER_NAME: "clic-kiusys-oke"
  API_B_ANIMAL_PATH: "/api/v2/animals"
  API_B_ADOPTANTE_PATH: "/api/v2/adoptantes"
  API_B_ADOPCION_PATH: "/api/v2/adopciones"
  API_C_IMAGEN_PATH: "/imagenes"
  API_C_NOTA_PATH: "/notas-medicas"
  API_C_DOCUMENTO_PATH: "/documentos-generados"
  INTEGRATION_STUB_WHEN_UNREACHABLE: "false"
  OBJECT_STORAGE_BACKEND: "local"
  OBJECT_STORAGE_LOCAL_DIR: "/data/object-storage"
  OCI_OS_BUCKET: "clic-kiusys-flow"
  OCI_OS_REGION: "sa-bogota-1"
